#include "item_m.h"

ItemMapping itemMap[] = {
    { 0x00, "Small Recovery" },
    { 0x01, "Medium Recovery" },
    { 0x02, "Large Recovery" },
    { 0x03, "Super Recovery" },
    { 0x04, "MP Floppy" },
    { 0x05, "Medium MP" },
    { 0x06, "Large MP" },
    { 0x07, "Double Flop" },
    { 0x08, "Various" },
    { 0x09, "Omnipotent" },
    { 0x0A, "Protection" },
    { 0x0B, "Restore" },
    { 0x0C, "Super Restore" },
    { 0x0D, "Bandage" },
    { 0x0E, "Medicine" },
    { 0x0F, "Offense Disk" },
    { 0x10, "Defense Disk" },
    { 0x11, "Hi Speed Disk" },
    { 0x12, "Omni Disk" },
    { 0x13, "S. Offense Disk" },
    { 0x14, "S. Defense Disk" },
    { 0x15, "S. Speed Disk" },
    { 0x16, "Auto Pilot" },
    { 0x17, "Offense Chip" },
    { 0x18, "Defense Chip" },
    { 0x19, "Brain Chip" },
    { 0x1A, "Quick Chip" },
    { 0x1B, "HP Chip" },
    { 0x1C, "MP Chip" },
    { 0x1D, "DV Chip A" },
    { 0x1E, "DV Chip D" },
    { 0x1F, "DV Chip E" },
    { 0x20, "Port. Potty" },
    { 0x21, "Trn.Manual" },
    { 0x22, "Rest Pillow" },
    { 0x23, "Enemy Repel" },
    { 0x24, "Enemy Bell" },
    { 0x25, "Health Shoe" },
    { 0x26, "Meat" },
    { 0x27, "Giant Meat" },
    { 0x28, "Sirloin" },
    { 0x29, "Super Carrot" },
    { 0x2A, "Hawk Radish" },
    { 0x2B, "Spiny Green" },
    { 0x2C, "Digimushroom" },
    { 0x2D, "Ice Mushroom" },
    { 0x2E, "Deluxe Mushroom" },
    { 0x2F, "Digipine" },
    { 0x30, "Blue Apple" },
    { 0x31, "Red Berry" },
    { 0x32, "Gold Acorn" },
    { 0x33, "Big Berry" },
    { 0x34, "Sweet Nut" },
    { 0x35, "Super Veggy" },
    { 0x36, "Pricklypear" },
    { 0x37, "Orange Banana" },
    { 0x38, "Power Fruit" },
    { 0x39, "Power Ice" },
    { 0x3A, "Speed Leaf" },
    { 0x3B, "Sage Fruit" },
    { 0x3C, "Muscle Yam" },
    { 0x3D, "Calm Berry" },
    { 0x3E, "Digianchovy" },
    { 0x3F, "Digisnapper" },
    { 0x40, "DigiTrout" },
    { 0x41, "Black Trout" },
    { 0x42, "Digicatfish" },
    { 0x43, "Digiseabass" },
    { 0x44, "Moldy Meat" },
    { 0x45, "Happymushroom" },
    { 0x46, "Chain Melon" },
    { 0x47, "Grey Claws" },
    { 0x48, "Fireball" },
    { 0x49, "Flamingwing" },
    { 0x4A, "Iron Hoof" },
    { 0x4B, "Mono Stone" },
    { 0x4C, "Steel Drill" },
    { 0x4D, "White Fang" },
    { 0x4E, "Black Wing" },
    { 0x4F, "Spike Club" },
    { 0x50, "Flamingmane" },
    { 0x51, "White Wing" },
    { 0x52, "Torn Tatter" },
    { 0x53, "Electo Ring" },
    { 0x54, "Rainbowhorn" },
    { 0x55, "Rooster" },
    { 0x56, "Unihorn" },
    { 0x57, "Horn Helmet" },
    { 0x58, "Scissor Jaw" },
    { 0x59, "Fertilizer" },
    { 0x5A, "Kogalaws" },
    { 0x5B, "Water Bottle" },
    { 0x5C, "North Star" },
    { 0x5D, "Red Shell" },
    { 0x5E, "Hard Scale" },
    { 0x5F, "Bluecrystal" },
    { 0x60, "Ice Crystal" },
    { 0x61, "Hair Grower" },
    { 0x62, "Sunglasses" },
    { 0x63, "Metal Part" },
    { 0x64, "Fatal Bone" },
    { 0x65, "Cyber Part" },
    { 0x66, "Mega Hand" },
    { 0x67, "Silver Ball" },
    { 0x68, "Metal Armor" },
    { 0x69, "Chainsaw" },
    { 0x6A, "Small Spear" },
    { 0x6B, "X Bandage" },
    { 0x6C, "Ray Gun" },
    { 0x6D, "Gold Banana" },
    { 0x6E, "Mysty Egg" },
    { 0x6F, "Red Ruby" },
    { 0x70, "Beetlepearl" },
    { 0x71, "Coral Charm" },
    { 0x72, "Moon Mirror" },
    { 0x73, "Blue Flute" },
    { 0x74, "Old Fishrod" },
    { 0x75, "Amazing Rod" },
    { 0x76, "Leomonstone" },
    { 0x77, "Mansion Key" },
    { 0x78, "Gear" },
    { 0x79, "Rain Plant" },
    { 0x7A, "Steak" },
    { 0x7B, "Frig Key" },
    { 0x7C, "AS Decoder" },
    { 0x7D, "Giga Hand" },
    { 0x7E, "Noble Mane" },
    { 0x7F, "Metal Banana" }
};

const int item_m_SIZE = sizeof(itemMap) / sizeof(ItemMapping);

char* getItemName(unsigned int searchId) {
    const char* itemName = "Unknown";
    for (int i = 0; i < item_m_SIZE; i++) {
        if (itemMap[i].value == searchId) {
            itemName = itemMap[i].name;
            break;
        }
    }
    return (char*)itemName;
}